//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//

package org.sapphire.appconsole.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AgeType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="AgeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="new"/>
 *     &lt;enumeration value="deleted"/>
 *     &lt;enumeration value="exists"/>
 *     &lt;enumeration value="updated"/>
 *     &lt;enumeration value="appcontext"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AgeType")
@XmlEnum
public enum AgeType {

	@XmlEnumValue("new")
	NEW("new"), @XmlEnumValue("deleted")
	DELETED("deleted"), @XmlEnumValue("exists")
	EXISTS("exists"), @XmlEnumValue("updated")
	UPDATED("updated"), @XmlEnumValue("appcontext")
	APPCONTEXT("appcontext");
	private final String value;

	AgeType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static AgeType fromValue(String v) {
		for (AgeType c : AgeType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
