//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EventType" type="{appconsole}EventOptionType"/>
 *         &lt;element name="EventActionType" type="{appconsole}EventActionType" minOccurs="0"/>
 *         &lt;element name="values" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="appContextVariable" type="{appconsole}Option" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "id",
    "eventType",
    "eventActionType",
    "values",
    "appContextVariable"
})
public class Event {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "EventType", required = true)
    protected EventOptionType eventType;
    @XmlElement(name = "EventActionType")
    protected EventActionType eventActionType;
    protected List<String> values;
    protected Option appContextVariable;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link EventOptionType }
     *     
     */
    public EventOptionType getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventOptionType }
     *     
     */
    public void setEventType(EventOptionType value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the eventActionType property.
     * 
     * @return
     *     possible object is
     *     {@link EventActionType }
     *     
     */
    public EventActionType getEventActionType() {
        return eventActionType;
    }

    /**
     * Sets the value of the eventActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventActionType }
     *     
     */
    public void setEventActionType(EventActionType value) {
        this.eventActionType = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the values property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValues() {
        if (values == null) {
            values = new ArrayList<String>();
        }
        return this.values;
    }

    /**
     * Gets the value of the appContextVariable property.
     * 
     * @return
     *     possible object is
     *     {@link Option }
     *     
     */
    public Option getAppContextVariable() {
        return appContextVariable;
    }

    /**
     * Sets the value of the appContextVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Option }
     *     
     */
    public void setAppContextVariable(Option value) {
        this.appContextVariable = value;
    }

}
