//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventOptionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventOptionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ADD_EDIT"/>
 *     &lt;enumeration value="ADD"/>
 *     &lt;enumeration value="EDIT"/>
 *     &lt;enumeration value="VIEW"/>
 *     &lt;enumeration value="GRAPH_VIEW"/>
 *     &lt;enumeration value="DELETE"/>
 *     &lt;enumeration value="CHANGE"/>
 *     &lt;enumeration value="SUBSCRIBE"/>
 *     &lt;enumeration value="ATTACH_APPCONTEXT_VARIABLE_LISTENER"/>
 *     &lt;enumeration value="SUBSCRIBE_APPCONTEXT_VARIABLE_CHANGE"/>
 *     &lt;enumeration value="SEPERATOR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventOptionType")
@XmlEnum
public enum EventOptionType {

    ADD_EDIT,
    ADD,
    EDIT,
    VIEW,
    GRAPH_VIEW,
    DELETE,
    CHANGE,
    SUBSCRIBE,
    ATTACH_APPCONTEXT_VARIABLE_LISTENER,
    SUBSCRIBE_APPCONTEXT_VARIABLE_CHANGE,
    SEPERATOR;

    public String value() {
        return name();
    }

    public static EventOptionType fromValue(String v) {
        return valueOf(v);
    }

}
