//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Filter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Filter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DbColumnName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataType" type="{appconsole}WidgetDataType"/>
 *         &lt;element name="Operator" type="{appconsole}OperatorType"/>
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ApiParameterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Filter", propOrder = {
    "id",
    "name",
    "dbColumnName",
    "dataType",
    "operator",
    "value",
    "apiParameterName",
    "category"
})
public class Filter {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "DbColumnName", required = true)
    protected String dbColumnName;
    @XmlElement(name = "DataType", required = true)
    protected WidgetDataType dataType;
    @XmlElement(name = "Operator", required = true)
    protected OperatorType operator;
    @XmlElement(name = "Value", required = true)
    protected String value;
    @XmlElement(name = "ApiParameterName", required = true)
    protected String apiParameterName;
    @XmlElement(name = "Category", required = true)
    protected String category;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dbColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbColumnName() {
        return dbColumnName;
    }

    /**
     * Sets the value of the dbColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbColumnName(String value) {
        this.dbColumnName = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link WidgetDataType }
     *     
     */
    public WidgetDataType getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WidgetDataType }
     *     
     */
    public void setDataType(WidgetDataType value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorType }
     *     
     */
    public OperatorType getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorType }
     *     
     */
    public void setOperator(OperatorType value) {
        this.operator = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the apiParameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiParameterName() {
        return apiParameterName;
    }

    /**
     * Sets the value of the apiParameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiParameterName(String value) {
        this.apiParameterName = value;
    }

	public String getCategory() {
		return category;
	}

	public void setCategory(String value) {
		this.category = value;
	}

    
}
