//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PageViewOptionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PageViewOptionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="popup"/>
 *     &lt;enumeration value="same-window"/>
 *     &lt;enumeration value="new-window"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PageViewOptionType")
@XmlEnum
public enum PageViewOptionType {

    @XmlEnumValue("popup")
    POPUP("popup"),
    @XmlEnumValue("same-window")
    SAME_WINDOW("same-window"),
    @XmlEnumValue("new-window")
    NEW_WINDOW("new-window");
    private final String value;

    PageViewOptionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PageViewOptionType fromValue(String v) {
        for (PageViewOptionType c: PageViewOptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
