//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Row complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Row">
 *   &lt;complexContent>
 *     &lt;extension base="{appconsole}UIComponent">
 *       &lt;sequence>
 *         &lt;element name="Cells" type="{appconsole}Cell" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="isBannerRow" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Row", propOrder = {
    "cells",
    "isBannerRow"
})
public class Row
    extends UIComponent
{

    @XmlElement(name = "Cells")
    protected List<Cell> cells;
    protected boolean isBannerRow;

    /**
     * Gets the value of the cells property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cells property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCells().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cell }
     * 
     * 
     */
    public List<Cell> getCells() {
        if (cells == null) {
            cells = new ArrayList<Cell>();
        }
        return this.cells;
    }

    /**
     * Gets the value of the isBannerRow property.
     * 
     */
    public boolean isIsBannerRow() {
        return isBannerRow;
    }

    /**
     * Sets the value of the isBannerRow property.
     * 
     */
    public void setIsBannerRow(boolean value) {
        this.isBannerRow = value;
    }

}
