//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Setting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Setting">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{appconsole}SettingType"/>
 *         &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DbColumnName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataType" type="{appconsole}WidgetDataType"/>
 *         &lt;element name="ApiParameterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Options" type="{appconsole}Option" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DefaultOption" type="{appconsole}Option"/>
 *         &lt;element name="NameQuery" type="{appconsole}NameQuery"/>
 *         &lt;element name="WidgetSettingType" type="{appconsole}WidgetSettingType"/>
 *         &lt;element name="AppContextVariables" type="{appconsole}Option" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Setting", propOrder = {
    "id",
    "label",
    "type",
    "defaultValue",
    "dbColumnName",
    "dataType",
    "apiParameterName",
    "options",
    "defaultOption",
    "nameQuery",
    "widgetSettingType",
    "appContextVariables",
    "category"
})
public class Setting {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Label", required = true)
    protected String label;
    @XmlElement(name = "Type", required = true)
    protected SettingType type;
    @XmlElement(name = "DefaultValue", required = true)
    protected String defaultValue;
    @XmlElement(name = "DbColumnName", required = true)
    protected String dbColumnName;
    @XmlElement(name = "DataType", required = true)
    protected WidgetDataType dataType;
    @XmlElement(name = "ApiParameterName", required = true)
    protected String apiParameterName;
    @XmlElement(name = "Options")
    protected List<Option> options;
    @XmlElement(name = "DefaultOption", required = true)
    protected Option defaultOption;
    @XmlElement(name = "NameQuery", required = true)
    protected NameQuery nameQuery;
    @XmlElement(name = "WidgetSettingType", required = true)
    protected WidgetSettingType widgetSettingType;
    @XmlElement(name = "AppContextVariables")
    protected List<Option> appContextVariables;
    @XmlElement(name = "Category", required = true)
    protected String category;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SettingType }
     *     
     */
    public SettingType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettingType }
     *     
     */
    public void setType(SettingType value) {
        this.type = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the dbColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbColumnName() {
        return dbColumnName;
    }

    /**
     * Sets the value of the dbColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbColumnName(String value) {
        this.dbColumnName = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link WidgetDataType }
     *     
     */
    public WidgetDataType getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WidgetDataType }
     *     
     */
    public void setDataType(WidgetDataType value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the apiParameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiParameterName() {
        return apiParameterName;
    }

    /**
     * Sets the value of the apiParameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiParameterName(String value) {
        this.apiParameterName = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the options property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Option }
     * 
     * 
     */
    public List<Option> getOptions() {
        if (options == null) {
            options = new ArrayList<Option>();
        }
        return this.options;
    }

    /**
     * Gets the value of the defaultOption property.
     * 
     * @return
     *     possible object is
     *     {@link Option }
     *     
     */
    public Option getDefaultOption() {
        return defaultOption;
    }

    /**
     * Sets the value of the defaultOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Option }
     *     
     */
    public void setDefaultOption(Option value) {
        this.defaultOption = value;
    }

    /**
     * Gets the value of the nameQuery property.
     * 
     * @return
     *     possible object is
     *     {@link NameQuery }
     *     
     */
    public NameQuery getNameQuery() {
        return nameQuery;
    }

    /**
     * Sets the value of the nameQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameQuery }
     *     
     */
    public void setNameQuery(NameQuery value) {
        this.nameQuery = value;
    }

    /**
     * Gets the value of the widgetSettingType property.
     * 
     * @return
     *     possible object is
     *     {@link WidgetSettingType }
     *     
     */
    public WidgetSettingType getWidgetSettingType() {
        return widgetSettingType;
    }

    /**
     * Sets the value of the widgetSettingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WidgetSettingType }
     *     
     */
    public void setWidgetSettingType(WidgetSettingType value) {
        this.widgetSettingType = value;
    }

    /**
     * Gets the value of the appContextVariables property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appContextVariables property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppContextVariables().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Option }
     * 
     * 
     */
    public List<Option> getAppContextVariables() {
        if (appContextVariables == null) {
            appContextVariables = new ArrayList<Option>();
        }
        return this.appContextVariables;
    }

	public String getCategory() {
		return category;
	}

	public void setCategory(String value) {
		this.category = value;
	}
    
	

}
