//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Table complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Table">
 *   &lt;complexContent>
 *     &lt;extension base="{appconsole}UIComponent">
 *       &lt;sequence>
 *         &lt;element name="NumberOfRows" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NumberOfCollumns" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;sequence>
 *           &lt;element name="Rows" type="{appconsole}Row" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Table", propOrder = {
    "numberOfRows",
    "numberOfCollumns",
    "rows"
})
public class Table
    extends UIComponent
{

    @XmlElement(name = "NumberOfRows")
    protected int numberOfRows;
    @XmlElement(name = "NumberOfCollumns")
    protected int numberOfCollumns;
    @XmlElement(name = "Rows")
    protected List<Row> rows;

    /**
     * Gets the value of the numberOfRows property.
     * 
     */
    public int getNumberOfRows() {
        return numberOfRows;
    }

    /**
     * Sets the value of the numberOfRows property.
     * 
     */
    public void setNumberOfRows(int value) {
        this.numberOfRows = value;
    }

    /**
     * Gets the value of the numberOfCollumns property.
     * 
     */
    public int getNumberOfCollumns() {
        return numberOfCollumns;
    }

    /**
     * Sets the value of the numberOfCollumns property.
     * 
     */
    public void setNumberOfCollumns(int value) {
        this.numberOfCollumns = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rows property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRows().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Row }
     * 
     * 
     */
    public List<Row> getRows() {
        if (rows == null) {
            rows = new ArrayList<Row>();
        }
        return this.rows;
    }

}
