//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ViewModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ViewModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LIST"/>
 *     &lt;enumeration value="LIST_GRAPH"/>
 *     &lt;enumeration value="EDIT"/>
 *     &lt;enumeration value="EDIT_ACTIVE_NOTE"/>
 *     &lt;enumeration value="SELECT"/>
 *     &lt;enumeration value="DETAIL"/>
 *     &lt;enumeration value="GRAPH_DETAIL"/>
 *     &lt;enumeration value="AS_BANNER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ViewModeType")
@XmlEnum
public enum ViewModeType {
	
    LIST,
    LIST_GRAPH,
    EDIT,
    EDIT_ACTIVE_NOTE,
    SELECT,
    DETAIL,
    GRAPH_DETAIL,
    AS_BANNER;

    public String value() {
        return name();
    }

    public static ViewModeType fromValue(String v) {
        return valueOf(v);
    }

}
