//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WidgetType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WidgetType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="medication"/>
 *     &lt;enumeration value="encounter"/>
 *     &lt;enumeration value="patients"/>
 *     &lt;enumeration value="vitalsigns"/>
 *     &lt;enumeration value="problems"/>
 *     &lt;enumeration value="recommendation"/>
 *     &lt;enumeration value="labtest"/>
 *     &lt;enumeration value="labpanel"/>
 *     &lt;enumeration value="adversereaction"/>
 *     &lt;enumeration value="launchapp"/>
 *     &lt;enumeration value="todolist"/>
 *     &lt;enumeration value="smartonfhir"/>
 *     &lt;enumeration value="allergyintolerance"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WidgetType")
@XmlEnum
public enum WidgetType {

    @XmlEnumValue("medication")
    MEDICATION("medication"),
    @XmlEnumValue("encounter")
    ENCOUNTER("encounter"),
    @XmlEnumValue("patients")
    PATIENTS("patients"),
    @XmlEnumValue("vitalsigns")
    VITALSIGNS("vitalsigns"),
    @XmlEnumValue("problems")
    PROBLEMS("problems"),
    @XmlEnumValue("recommendation")
    RECOMMENDATION("recommendation"),
    @XmlEnumValue("labtest")
    LABTEST("labtest"),
    @XmlEnumValue("labpanel")
    LABPANEL("labpanel"),
    @XmlEnumValue("adversereaction")
    ADVERSEREACTION("adversereaction"),
    @XmlEnumValue("launchapp")
    LAUNCHAPP("launchapp"),
    @XmlEnumValue("todolist")
    TODOLIST("todolist"),
    @XmlEnumValue("smartonfhir")
    SMARTONFHIR("smartonfhir"),
    @XmlEnumValue("allergyintolerance")
    ALLERGYINTOLERANCE("allergyintolerance");
    private final String value;

    WidgetType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WidgetType fromValue(String v) {
        for (WidgetType c: WidgetType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
