//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 08:41:16 PM IST 
//


package org.sapphire.appconsole.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WidgetSettingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WidgetSettingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FILTER"/>
 *     &lt;enumeration value="PROPERTY"/>
 *     &lt;enumeration value="NAMED_QUERY"/>
 *     &lt;enumeration value="APP_CONTEXT_VARIABLES"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WidgetSettingType")
@XmlEnum
public enum WidgetSettingType {

    FILTER,
    PROPERTY,
    NAMED_QUERY,
    APP_CONTEXT_VARIABLES;

    public String value() {
        return name();
    }

    public static WidgetSettingType fromValue(String v) {
        return valueOf(v);
    }

}
